### ISSUE TITLE
Query reduction throughout the application

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#190]
There is a lot of information that is being pulled in from the database on various pages. 

At the moment, this information is queried at a relatively low level - that is, queried close to the component where it is used. Conceptually, we would be querying X in each component in the diagram below.

![Untitled Diagram drawio](https://user-images.githubusercontent.com/2946344/148192369-159fc4a2-3b7e-48de-9de8-4c2deb2cdf22.png)

If we query the same information in each component, we have a total of 3 queries. If we would query in the page, and pass the information to each component, we would reduce the queries to 1.

This is happening throughout the application and may affect the performance, depending on the scale at which this happens.

## Todo

- [ ] Create a full inventory of queries for the various pages (e.g., using [draw.io](https://draw.io))
- [ ] Find common queries within a page across components
- [ ] Identify which queries can be "promoted" to higher level components to reduce queries
- [ ] Implement

**Comment by chartgerink** [comment]
An initial assessment.

![Untitled Diagram drawio(1)](https://user-images.githubusercontent.com/2946344/148379322-819c9bd3-ca66-4d98-8db9-3116dcdd54b4.png)

It seems like the main gain here is related to the workspace and user queries. Elevating those up in the page and passing it down to individual components like `Navbar` and chldren, may reduce the number of queries necessary.

In that sense, this may relate to #33 as well, if that can make certain queries superfluous to begin with.
