### ISSUE TITLE
Factor out copywriting to `en.json`

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#589]
In order to prepare for localization, we need to factor out all text into the `/langs/en.json` file. This is a continuation of the work in #581.

In essence, we need to structure the [`/langs/en.json`](https://github.com/libscie/ResearchEquals.com/blob/main/langs/en.json) file with a lot of keys and strings that will be the text presented in English. For example:

```
{
  "translation": {
    "hero": "Step by step publishing of your research",
    "hero_subtitle": "A new publishing format: Research modules."
  }
}
```

Part of this issue is to find a good structure for the key and to ensure all the text that would need to be translated is in there. Please make sure to not forget checking all the non-visual aspects like `aria-label` and others!

We are starting to document the work for localization over in the Wiki - additional edits there are welcome as necessary while working on this.

## Todo

- [ ] Add `i18` to each page (`import "../core/i18n"`)
- [ ] Add `useTranslation` to components (for the `t` method)
- [ ] Consistent naming scheme for text
- [ ] Actually factoring out the strings

**Comment by chartgerink** [comment]
Closing this as it's been open for a while and we're clearly not doing it at the moment. Will move to our backlog so we don't lose track.
