### ISSUE TITLE
Add ROR (affiliation) ID to authors

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#630]
We currently have no way for authors to indicate their affiliation. 📚 Let's change that! In this issue we track the work (note that if there's no milestone, we are not actively working on this and it's a feature request only).

The [ROR (Research Organization Registry)](https://ror.org/) provides stable identifiers for organizations that a researcher may be a part of. It is community moderated and suggestions are being incorporated on an ongoing basis. This seems to be becoming the new standard.

If we have affiliations, we could also include a `org/<id>` route at some point potentially and present all people we know about from a specific affiliation. This could be taken into account in the design.

## Resources 

- [Include ROR IDs in DOI metadata](https://ror.readme.io/docs/include-ror-ids-in-doi-metadata)
- ROR API

## To-do

- [ ] Update database schema
- [ ] Update CrossRef metadata generation
- [ ] Include a way for authors to search, find, and add their affiliation

## Open questions

- Could we allow for multiple affiliations? Do we want to? ([see CrossRef schema](https://data.crossref.org/reports/help/schema_doc/5.3.1/index.html))
